### ISSUE TITLE
Investigate multi-device bug on Ubuntu

### ISSUE THREAD

**Issue by seclorum** [kallaballa/MidiPatch#47]
Testing today, it was discovered that using mutliple-device leads to dropped MIDI events in midipatch.  

With the following run configuration, -m5=akai-kpk25,6=minilab:

`
$ ./run.sh -r 44100 -m 5,6 -a 0 -o 52 -v 3 -p lua/sin.lua 
`
.. errors such as:

> 
> 2019-11-09 22:17:35.415 INFO  [Unknown] [log_info@55] Initialize MIDI: Port: 5
> 2019-11-09 22:17:35.420 INFO  [Unknown] [log_info@55] Initialize MIDI: Port: 6
> 2019-11-09 22:17:35.420 INFO  [Unknown] [log_info@55] Initialize Audio: Port: 0 channels: 2 rate: 44100 frames: 512
> MIDI Note ON   C: 7 N: 81 V: 40
> MIDI Note ON   C: 7 N: 81 V: 40
> MIDI Note ON   C: 7 N: 87 V: 9
> MIDI Note ON   C: 7 N: 87 V: 9
> MIDI Note ON   C: 7 N: 84 V: 69
> MIDI Note OFF  C: 7 N: 87
> MIDI Note OFF  C: 7 N: 81
> MIDI Note ON   C: 7 N: 81 V: 50
> MidiInAlsa::alsaMidiHandler: unknown MIDI input error!
> MidiInAlsa::alsaMidiHandler: unknown MIDI input error!
> MIDI Note OFF  C: 7 N: 84
> MIDI Note ON   C: 7 N: 89 V: 37
> MIDI Note OFF  C: 7 N: 81
> MIDI Note ON   C: 7 N: 84 V: 72
> MIDI Note ON   C: 7 N: 81 V: 74
> MIDI Note OFF  C: 7 N: 84
> MIDI Note OFF  C: 7 N: 89
> MIDI Note ON   C: 7 N: 88 V: 83
> MIDI Note OFF  C: 7 N: 81
> MIDI Note ON   C: 7 N: 84 V: 67
> MIDI Note OFF  C: 7 N: 88
> MIDI Note ON   C: 7 N: 81 V: 69
> MIDI Note ON   C: 7 N: 89 V: 34
> MIDI Note OFF  C: 7 N: 84
> MIDI Note ON   C: 7 N: 88 V: 66
> MIDI Note OFF  C: 7 N: 81
> MIDI Note OFF  C: 7 N: 89
> MIDI Note ON   C: 7 N: 84 V: 98
> MidiInAlsa::alsaMidiHandler: unknown MIDI input error!
> MIDI Note OFF  C: MidiInAlsa::alsaMidiHandler: unknown MIDI input error!
> MIDI Note OFF  C: 7 N: 88
> MIDI Note ON   C: 7 N: 81 V: 56
> MIDI Note ON   C: 7 N: 89 V: 72
> MIDI Note ON   C: 7 N: 88 V: 79

.. occur when **"-m  5,6"**, significantly ,. but not when either **"-m 5"** or **"-m 6"** parameters.

**Comment by seclorum** [comment]
(bug happens on both JACK and ALSA buildconfigs, but Alsa produces better error messages..)

**Comment by kallaballa** [comment]
upgrade to RtMidi 4.0 fix it
